FOPTIM = -O2
FFLAGS = $(FOPTIM)
LDFLAGS = -static -L$(PGPLOTDIR) $(PGLIBS) -L$(X11LIBDIR) -L$(GSLDIR) \
	-L$(CGRAPHDIR) -L$(DISLIN) $(DISLINLIBS) $(CGRAPH) $(LIBS) -lm -ldl -lpthread
CFLAGS = -static
FC     = g77
CC     = gcc
