FOPTIM  = -O2
FFLAGS  = $(FOPTIM)
LDFLAGS = -Bstatic -L$(GSLDIR) -L$(PLPLOTLIBDIR) $(PLLIBS) -L$(X11LIBDIR) $(LIBS) -lm -ldl -lpthread
CFLAGS  = -Bstatic -I/usr/local/include/plplot
FC      = g77
CC      = gcc
